version: '3.8'

volumes:
  dbdata:

services:
  database:
    image: mariadb:10.7
    ports:
      - "3306"
    environment:
      - MYSQL_DATABASE=inventory_data
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      net:
    restart: always

  # Web Server
  webserver:
    image: nginx:stable-alpine
    volumes:
      - ./docker/webserver/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/webserver/nginx/www.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/application
      - ./docker/webserver/public/robots.disallow.txt:/application/public/robots.txt:ro
    environment:
      - VIRTUAL_HOST=inventory_track.local.com
      # - ENABLE_ACME=true
    networks:
      expose_network:
      net:
    depends_on:
      - php_fpm
    restart: always

  # Web Application
  php_fpm:
    build:
      context: ./docker/webapp
      dockerfile: Dockerfile
    volumes:
      - ./docker/webapp/php-ini-overrides.ini:/usr/local/etc/php/conf.d/default.ini:ro
      - ./docker/webapp/php-fpm-overrides.conf:/usr/local/etc/php-fpm.d/zz-pm.conf:ro
      - ./:/application
      - ./docker/webserver/public/robots.disallow.txt:/application/public/robots.txt:ro
    networks:
      net:
    restart: always

#  # Mail testing
#  maildev:
#    image: djfarrelly/maildev:latest
#    networks:
#      net:
#    restart: always
#    ports:
#      - "80"
#
#  # Redis
#  redis:
#    image: redis:5.0.0-alpine
#    ports:
#      - "6379"
#    networks:
#      net:
#    restart: always
#
#  # Queue worker
#  worker:
#    build:  ./docker/worker
#    working_dir: /application
#    restart: always
#    volumes:
#      - ./:/application
#    environment:
#      - QUEUE=example
#    networks:
#      expose_network:
#      net:
#
networks:
  # Join proxy network for exposing http services
  expose_network:
    external:
      name: web_proxy
  # Internal network for this project
  net:
